language: perl
cache:
    - apt
    - ccache
notifications:
  irc: "chat.freenode.net#lua-resty-waf"
  webhooks: https://www.cryptobells.com/endpoint
env:
  global:
    - V_OPENRESTY=1.11.2.2
    - DATE=20170216
  matrix:
    - TEST=unit RUNNER='perl'
    - TEST=acceptance RUNNER='perl'
    - TEST=regression RUNNER='perl'
    - TEST=translate RUNNER='perl'
    - TEST=translation RUNNER='rebusted -o=TAP'
services:
    - memcached
    - redis
install:
    - cpanm -v --notest Test::Nginx Test::More Exporter::Declare Test::Exception Test::MockModule;
before_script:
    - export PATH=/usr/local/openresty/bin/:$PATH
    - sudo apt-get update -q
    - sudo apt-get install lua5.1 liblua5.1-0-dev luarocks libpcre3-dev -y
    - sudo wget -O /usr/local/bin/rebusted https://raw.githubusercontent.com/thibaultcha/lua-resty-busted/master/bin/busted
    - sudo chmod +x /usr/local/bin/rebusted
    - wget https://s3.amazonaws.com/p0pr0ck5-data/openresty-$V_OPENRESTY-$DATE.tar.bz2
    - sudo tar -jxvf openresty-$V_OPENRESTY-$DATE.tar.bz2 -C /usr/local/
    - make
    - sudo make install-link install-rocks
    - sudo luarocks install lrexlib-pcre 2.7.2-1 PCRE_LIBDIR=/lib/x86_64-linux-gnu
script:
    - PATH=/usr/local/openresty/nginx/sbin:$PATH prove -v --exec "$RUNNER" -r t/$TEST/*
    - ./tools/lua-releng -L
